name: OSCAR examples
url: sebasguts.github.io/oscarexamples
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 12

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
