name: OSCAR examples
url: sebasguts.github.io/OSCARDemo/
description: Insert tagline here

permalink: /worksheets/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 12

baseurl: /OSCARDemo

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
