name: OSCAR examples
url: https://sebasguts.github.io/OSCARDemo
description: Insert tagline here

permalink: /worksheets/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 12

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
